# Form implementation generated from reading ui file '/Users/lennon/Projects/Time_Integrater/ti/UI/rawUI/rawSettingPage.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SettingPage(object):
    def setupUi(self, SettingPage):
        SettingPage.setObjectName("SettingPage")
        SettingPage.resize(568, 401)
        self.verticalLayout = QtWidgets.QVBoxLayout(SettingPage)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=SettingPage)
        self.label.setMinimumSize(QtCore.QSize(0, 45))
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.widget = QtWidgets.QWidget(parent=SettingPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.frame_3 = QtWidgets.QFrame(parent=self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.uidButton = QtWidgets.QToolButton(parent=self.frame_3)
        self.uidButton.setMinimumSize(QtCore.QSize(90, 30))
        self.uidButton.setObjectName("uidButton")
        self.horizontalLayout.addWidget(self.uidButton)
        self.toolButton_5 = QtWidgets.QToolButton(parent=self.frame_3)
        self.toolButton_5.setMinimumSize(QtCore.QSize(90, 30))
        self.toolButton_5.setObjectName("toolButton_5")
        self.horizontalLayout.addWidget(self.toolButton_5)
        self.toolButton_3 = QtWidgets.QToolButton(parent=self.frame_3)
        self.toolButton_3.setMinimumSize(QtCore.QSize(90, 30))
        self.toolButton_3.setObjectName("toolButton_3")
        self.horizontalLayout.addWidget(self.toolButton_3)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.label_3 = QtWidgets.QLabel(parent=self.widget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.frame_2 = QtWidgets.QFrame(parent=self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2.addWidget(self.frame_2)
        self.verticalLayout.addWidget(self.widget)
        self.pageSwitchFrame = PageSwitchFrame(parent=SettingPage)
        self.pageSwitchFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.pageSwitchFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.pageSwitchFrame.setObjectName("pageSwitchFrame")
        self.verticalLayout.addWidget(self.pageSwitchFrame)

        self.retranslateUi(SettingPage)
        QtCore.QMetaObject.connectSlotsByName(SettingPage)

    def retranslateUi(self, SettingPage):
        _translate = QtCore.QCoreApplication.translate
        SettingPage.setWindowTitle(_translate("SettingPage", "Form"))
        self.label.setText(_translate("SettingPage", "<html><head/><body><p><span style=\" font-size:36pt; font-weight:700;\">Strategy and Setting</span></p></body></html>"))
        self.label_2.setText(_translate("SettingPage", "Dev Tools - Do not use unless you really know what ur doing"))
        self.uidButton.setText(_translate("SettingPage", "add uid to record"))
        self.toolButton_5.setText(_translate("SettingPage", "..."))
        self.toolButton_3.setText(_translate("SettingPage", "..."))
        self.label_3.setText(_translate("SettingPage", "TextLabel"))
from ti.UI.views.pageSwitchFrame import PageSwitchFrame
