# pytest.ini

[pytest]
# 这一行，明确地告诉pytest：“你的所有‘寻路’操作，都应该相对于这个项目的根目录。”
# 它让pytest知道，'ti'和'Data'都是顶级的包。
pythonpath = .

# 这一行，明确地告诉pytest：“你只需要去'tests'这个文件夹里，寻找你的‘孩子们’。”
# 这避免了它去扫描项目中的其他目录，提高了效率，也避免了冲突。
testpaths = tests