@startuml
participant "MainCoodinator" as coodinator 
participant "CardController" as controller
participant "InsightCards" as ui
participant "InterventionService" as service 

activate coodinator

title 铺垫:检测是否需要干涉

' 检测
monitor --> coodinator: _on_promise_detected()
deactivate monitor

coodinator -> ui: showPromise()
activate ui

ref over ui: 我不确定这里需不需要一张图

ui -> service: 用户做出选择(data)
activate service

service --> ui: change_appearance
deactivate service

ui --> controller: return None
deactivate ui
activate controller

controller --> coodinator: return None
deactivate controller

@enduml