
participant "MainCoodinator" as coodinator
participant "CardController" as controller
participant "InsightCards" as ui
participant "InterventionService" as service 
participant "RealTimeMonitorService" as monitor

title 开场: 用户查看界面 | 创建干涉实体

activate coodinator

' 切换界面到AP: 这一部分和当前的不一样
coodinator -> controller: show_analysis_page()
activate controller

controller -> ui: display()
activate ui

ui --> controller: 展示完成
deactivate ui

' 用户和UI交互
ref over ui: [1]Intervention_dataflow_User_Interaction

ui --> controller: _on_user_action(data)


' 创建干涉实体逻辑类
controller -> service: create_new_intervention(UI)
activate service

service --> controller: return None 创建完毕
deactivate service

controller -> monitor: setNewWarning()
activate monitor

monitor --> controller: return True
deactivate monitor

controller --> coodinator: return None
deactivate controller

ref over service: 这里可能需要一张关于创建的动态图
