@startuml
title: Intervention_Initialization

' 问题在于，没写依赖

participant "MainCoodinator" as coodinator 
participant "CardController" as controller
participant "Conditional_ReportGenerator" as generator
participant "InterventionLogger" as logger
participant "InterventionService" as service

activate coodinator
group 准备: 卡片和干涉创建
    ' 创建报告
    coodinator -> controller: create_yesterday_report()
    activate controller
    
    ' 创建干涉卡片UI
    controller -> generator: create_report()
    activate generator

    ref over generator
        [1]InterventionCard_init.puml
        干涉卡片创建完毕
        ' Documents/umls/1/[1]InterventionCard_init.puml
    end ref

    generator --> controller: return cards
    deactivate generator

    controller -> ui: fill_card()
    activate ui

    ui -> controller: return AnalysisPage
    deactivate ui

    controller -> coodinator: return 页面创建完毕
    deactivate controller
    
    coodinator -> service: __init__()
    activate service

    service --> coodinator: return InterventionService
    deactivate service

    coodinator -> monitor: __init__()
    activate monitor

    monitor --> coodinator: return RealTimeMonitorService
    deactivate monitor

    coodinator -> logger: __init__()
    activate logger

    logger --> coodinator: return InterventionLogger
    deactivate logger
end group

group 后记: 整理干涉实体
    coodinator -> logger: clean_up_intervention
    activate logger

    logger -> service: get_and_reset_intervention()
    activate service

    ref over logger: 这里需要一张动态图来表示获取和存储
    
    service --> logger: return interventions: list
    deactivate service

    logger --> coodinator: return None, 完成清理
    deactivate logger
end group
@enduml