@startuml
' 功能:
' 0. 卡片+干涉创建
' 1. 创建干涉实体
' 2. 检测是否干涉
' 3. 干涉操作

title: 干涉功能流程图

participant "MainCoodinator" as coodinator 
participant "CardController" as controller
participant "RealTimeMonitorService" as monitor

' 一切的开始
activate coodinator

group 初始化的时候
    coodinator -> controller: create_yesterday_report()
    activate controller

    controller --> coodinator: return None: 完成初始化

    ref over controller
        Documents/umls/0/
        [0.5]Intervention_Init.puml
    end ref
end group

group 用户查看的时候
    controller -> monitor: __init__
    activate monitor
    ' 做了简略化处理
    ref over controller
        Documents/umls/0/
        [0.5]Intervention_Generation.puml
    end ref 
end group

group 用户输入的时候
    monitor --> coodinator: _on_promise_detected()
    deactivate monitor

    ref over coodinator
        Documents/umls/0/
        [0.5]Intervention_Detect.puml
    end ref
end group




@enduml