# Form implementation generated from reading ui file '/Users/lennon/Projects/Time_Integrater/ti/UI/rawUI/rawDateSelectionFrame.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dateSelection(object):
    def setupUi(self, dateSelection):
        dateSelection.setObjectName("dateSelection")
        dateSelection.resize(404, 662)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(dateSelection.sizePolicy().hasHeightForWidth())
        dateSelection.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(dateSelection)
        self.verticalLayout.setObjectName("verticalLayout")
        self.calendarDateSelection = QtWidgets.QCalendarWidget(parent=dateSelection)
        self.calendarDateSelection.setObjectName("calendarDateSelection")
        self.verticalLayout.addWidget(self.calendarDateSelection)
        self.actionUnitList = QtWidgets.QListWidget(parent=dateSelection)
        self.actionUnitList.setObjectName("actionUnitList")
        self.verticalLayout.addWidget(self.actionUnitList)

        self.retranslateUi(dateSelection)
        QtCore.QMetaObject.connectSlotsByName(dateSelection)

    def retranslateUi(self, dateSelection):
        _translate = QtCore.QCoreApplication.translate
        dateSelection.setWindowTitle(_translate("dateSelection", "Form"))
