# Form implementation generated from reading ui file '/Users/lennon/Library/Mobile Documents/com~apple~CloudDocs/Useful files/Projects/Time_Integrater/QtUI/rawUI/rawDailyTrendCard.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_trendCard(object):
    def setupUi(self, trendCard):
        trendCard.setObjectName("trendCard")
        trendCard.resize(427, 180)
        trendCard.setMinimumSize(QtCore.QSize(0, 180))
        trendCard.setMaximumSize(QtCore.QSize(16777215, 180))
        self.horizontalLayout = QtWidgets.QHBoxLayout(trendCard)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cardsFrame = QtWidgets.QFrame(parent=trendCard)
        self.cardsFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.cardsFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.cardsFrame.setObjectName("cardsFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.cardsFrame)
        self.verticalLayout.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cardIconWidget = QtWidgets.QWidget(parent=self.cardsFrame)
        self.cardIconWidget.setObjectName("cardIconWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.cardIconWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.iconLabel = QtWidgets.QLabel(parent=self.cardIconWidget)
        self.iconLabel.setMinimumSize(QtCore.QSize(30, 0))
        self.iconLabel.setText("")
        self.iconLabel.setObjectName("iconLabel")
        self.horizontalLayout_2.addWidget(self.iconLabel)
        self.titleLabel = QtWidgets.QLabel(parent=self.cardIconWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleLabel.sizePolicy().hasHeightForWidth())
        self.titleLabel.setSizePolicy(sizePolicy)
        self.titleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.horizontalLayout_2.addWidget(self.titleLabel)
        self.verticalLayout.addWidget(self.cardIconWidget)
        self.sementicFrame = QtWidgets.QWidget(parent=self.cardsFrame)
        self.sementicFrame.setObjectName("sementicFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.sementicFrame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.sementicLabel = QtWidgets.QLabel(parent=self.sementicFrame)
        self.sementicLabel.setText("")
        self.sementicLabel.setObjectName("sementicLabel")
        self.verticalLayout_2.addWidget(self.sementicLabel)
        self.verticalLayout.addWidget(self.sementicFrame)
        self.judgementFrame = QtWidgets.QWidget(parent=self.cardsFrame)
        self.judgementFrame.setObjectName("judgementFrame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.judgementFrame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.judgementLabel = QtWidgets.QLabel(parent=self.judgementFrame)
        self.judgementLabel.setText("")
        self.judgementLabel.setObjectName("judgementLabel")
        self.verticalLayout_3.addWidget(self.judgementLabel)
        self.verticalLayout.addWidget(self.judgementFrame)
        self.horizontalLayout.addWidget(self.cardsFrame)

        self.retranslateUi(trendCard)
        QtCore.QMetaObject.connectSlotsByName(trendCard)

    def retranslateUi(self, trendCard):
        _translate = QtCore.QCoreApplication.translate
        trendCard.setWindowTitle(_translate("trendCard", "Form"))
        self.titleLabel.setText(_translate("trendCard", "<html><head/><body><p><span style=\" font-size:36pt;\">test</span></p></body></html>"))
