# Form implementation generated from reading ui file '/Users/lennon/Library/Mobile Documents/com~apple~CloudDocs/Useful files/Projects/Time_Integrater/QtUI/views/rawUI/rawDailyTrendCard.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_trendCard(object):
    def setupUi(self, trendCard):
        trendCard.setObjectName("trendCard")
        trendCard.resize(409, 188)
        self.horizontalLayout = QtWidgets.QHBoxLayout(trendCard)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cardsFrame = QtWidgets.QFrame(parent=trendCard)
        self.cardsFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.cardsFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.cardsFrame.setObjectName("cardsFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.cardsFrame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cardIconWidget = QtWidgets.QWidget(parent=self.cardsFrame)
        self.cardIconWidget.setObjectName("cardIconWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.cardIconWidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.iconLabel = QtWidgets.QLabel(parent=self.cardIconWidget)
        self.iconLabel.setText("")
        self.iconLabel.setObjectName("iconLabel")
        self.horizontalLayout_2.addWidget(self.iconLabel)
        self.verticalLayout.addWidget(self.cardIconWidget)
        self.cardTextWidget = QtWidgets.QWidget(parent=self.cardsFrame)
        self.cardTextWidget.setObjectName("cardTextWidget")
        self.verticalLayout.addWidget(self.cardTextWidget)
        self.cardOptionWidget = QtWidgets.QWidget(parent=self.cardsFrame)
        self.cardOptionWidget.setObjectName("cardOptionWidget")
        self.verticalLayout.addWidget(self.cardOptionWidget)
        self.horizontalLayout.addWidget(self.cardsFrame)

        self.retranslateUi(trendCard)
        QtCore.QMetaObject.connectSlotsByName(trendCard)

    def retranslateUi(self, trendCard):
        _translate = QtCore.QCoreApplication.translate
        trendCard.setWindowTitle(_translate("trendCard", "Form"))
