# Form implementation generated from reading ui file '/Users/lennon/Library/Mobile Documents/com~apple~CloudDocs/Useful files/Projects/Time_Integrater/QtUI/views/rawUI/rawBulkEnterFrame.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_bulkEnterFrame(object):
    def setupUi(self, bulkEnterFrame):
        bulkEnterFrame.setObjectName("bulkEnterFrame")
        bulkEnterFrame.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(bulkEnterFrame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.bulkTextEdit = QtWidgets.QTextEdit(parent=bulkEnterFrame)
        self.bulkTextEdit.setObjectName("bulkTextEdit")
        self.verticalLayout.addWidget(self.bulkTextEdit)
        self.submitButton = QtWidgets.QToolButton(parent=bulkEnterFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.submitButton.sizePolicy().hasHeightForWidth())
        self.submitButton.setSizePolicy(sizePolicy)
        self.submitButton.setObjectName("submitButton")
        self.verticalLayout.addWidget(self.submitButton)

        self.retranslateUi(bulkEnterFrame)
        QtCore.QMetaObject.connectSlotsByName(bulkEnterFrame)

    def retranslateUi(self, bulkEnterFrame):
        _translate = QtCore.QCoreApplication.translate
        bulkEnterFrame.setWindowTitle(_translate("bulkEnterFrame", "Form"))
        self.submitButton.setText(_translate("bulkEnterFrame", "..."))
