# Form implementation generated from reading ui file '/Users/lennon/Projects/Time_Integrater/ti/features/core_view/view/rawCorePage.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

from ti.view.pageSwitchFrame import PageSwitchFrame


class Ui_main_page(object):
    def setupUi(self, main_page):
        main_page.setObjectName("main_page")
        main_page.resize(876, 647)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(main_page.sizePolicy().hasHeightForWidth())
        main_page.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(main_page)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mainFrame = QtWidgets.QWidget(parent=main_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainFrame.sizePolicy().hasHeightForWidth())
        self.mainFrame.setSizePolicy(sizePolicy)
        self.mainFrame.setObjectName("mainFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.mainFrame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mode_change_frame = QtWidgets.QFrame(parent=self.mainFrame)
        self.mode_change_frame.setMinimumSize(QtCore.QSize(100, 0))
        self.mode_change_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.mode_change_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.mode_change_frame.setObjectName("mode_change_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.mode_change_frame)
        self.verticalLayout_2.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.mode_change_frame)
        self.mainFrame_2 = QtWidgets.QFrame(parent=self.mainFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainFrame_2.sizePolicy().hasHeightForWidth())
        self.mainFrame_2.setSizePolicy(sizePolicy)
        self.mainFrame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.mainFrame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.mainFrame_2.setObjectName("mainFrame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.mainFrame_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.mainFrame_2)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.horizontalLayout_3.addWidget(self.stackedWidget)
        self.horizontalLayout.addWidget(self.mainFrame_2)
        self.verticalLayout.addWidget(self.mainFrame)
        self.pageSwitchFrameBase = PageSwitchFrame(parent=main_page)
        self.pageSwitchFrameBase.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.pageSwitchFrameBase.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.pageSwitchFrameBase.setObjectName("pageSwitchFrameBase")
        self.verticalLayout.addWidget(self.pageSwitchFrameBase)

        self.retranslateUi(main_page)
        QtCore.QMetaObject.connectSlotsByName(main_page)

    def retranslateUi(self, main_page):
        _translate = QtCore.QCoreApplication.translate
        main_page.setWindowTitle(_translate("main_page", "Form"))

