# Form implementation generated from reading ui file '/Users/lennon/Library/Mobile Documents/com~apple~CloudDocs/Useful files/Projects/Time_Integrater/QtUI/views/rawUI/rawEditorFrame.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_editorFrame(object):
    def setupUi(self, editorFrame):
        editorFrame.setObjectName("editorFrame")
        editorFrame.resize(689, 508)
        self.verticalLayout = QtWidgets.QVBoxLayout(editorFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mainFrame = QtWidgets.QFrame(parent=editorFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainFrame.sizePolicy().hasHeightForWidth())
        self.mainFrame.setSizePolicy(sizePolicy)
        self.mainFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.mainFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.mainFrame.setObjectName("mainFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.mainFrame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.fastEnterFrame = QtWidgets.QFrame(parent=self.mainFrame)
        self.fastEnterFrame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.fastEnterFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.fastEnterFrame.setObjectName("fastEnterFrame")
        self.verticalLayout_2.addWidget(self.fastEnterFrame)
        self.propertyFrame = QtWidgets.QFrame(parent=self.mainFrame)
        self.propertyFrame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.propertyFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.propertyFrame.setObjectName("propertyFrame")
        self.verticalLayout_2.addWidget(self.propertyFrame)
        self.verticalLayout.addWidget(self.mainFrame)
        self.bottomToolFrame = QtWidgets.QFrame(parent=editorFrame)
        self.bottomToolFrame.setMinimumSize(QtCore.QSize(0, 60))
        self.bottomToolFrame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.bottomToolFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.bottomToolFrame.setObjectName("bottomToolFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.bottomToolFrame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftSwitchButton = QtWidgets.QToolButton(parent=self.bottomToolFrame)
        self.leftSwitchButton.setMinimumSize(QtCore.QSize(60, 60))
        self.leftSwitchButton.setObjectName("leftSwitchButton")
        self.horizontalLayout.addWidget(self.leftSwitchButton)
        self.confirmButton = QtWidgets.QToolButton(parent=self.bottomToolFrame)
        self.confirmButton.setMinimumSize(QtCore.QSize(60, 60))
        self.confirmButton.setObjectName("confirmButton")
        self.horizontalLayout.addWidget(self.confirmButton)
        self.rightSwitchButton = QtWidgets.QToolButton(parent=self.bottomToolFrame)
        self.rightSwitchButton.setMinimumSize(QtCore.QSize(60, 60))
        self.rightSwitchButton.setObjectName("rightSwitchButton")
        self.horizontalLayout.addWidget(self.rightSwitchButton)
        self.verticalLayout.addWidget(self.bottomToolFrame)

        self.retranslateUi(editorFrame)
        QtCore.QMetaObject.connectSlotsByName(editorFrame)

    def retranslateUi(self, editorFrame):
        _translate = QtCore.QCoreApplication.translate
        editorFrame.setWindowTitle(_translate("editorFrame", "Form"))
        self.leftSwitchButton.setText(_translate("editorFrame", "<-"))
        self.confirmButton.setText(_translate("editorFrame", "confirm"))
        self.rightSwitchButton.setText(_translate("editorFrame", "->"))
