# Form implementation generated from reading ui file '/Users/lennon/Library/Mobile Documents/com~apple~CloudDocs/Useful files/Projects/Time_Integrater/QtUI/views/rawUI/rawInputEnterFrame.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_inputEnterFrame(object):
    def setupUi(self, inputEnterFrame):
        inputEnterFrame.setObjectName("inputEnterFrame")
        inputEnterFrame.resize(722, 488)
        self.verticalLayout = QtWidgets.QVBoxLayout(inputEnterFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.fastEnterFrameBase = FastEnterFrame(parent=inputEnterFrame)
        self.fastEnterFrameBase.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.fastEnterFrameBase.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.fastEnterFrameBase.setObjectName("fastEnterFrameBase")
        self.verticalLayout.addWidget(self.fastEnterFrameBase)
        self.propertyEnterFrameBase = PropertyEnterFrame(parent=inputEnterFrame)
        self.propertyEnterFrameBase.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.propertyEnterFrameBase.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.propertyEnterFrameBase.setObjectName("propertyEnterFrameBase")
        self.verticalLayout.addWidget(self.propertyEnterFrameBase)

        self.retranslateUi(inputEnterFrame)
        QtCore.QMetaObject.connectSlotsByName(inputEnterFrame)

    def retranslateUi(self, inputEnterFrame):
        _translate = QtCore.QCoreApplication.translate
        inputEnterFrame.setWindowTitle(_translate("inputEnterFrame", "Form"))
from QtUI.views.fastEnterFrame import FastEnterFrame
from QtUI.views.propertyEnterFrame import PropertyEnterFrame
