# Form implementation generated from reading ui file '/Users/lennon/Library/Mobile Documents/com~apple~CloudDocs/Useful files/Projects/Time_Integrater/QtUI/views/rawUI/rawEditorFrame.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_editorFrame(object):
    def setupUi(self, editorFrame):
        editorFrame.setObjectName("editorFrame")
        editorFrame.resize(689, 508)
        self.verticalLayout = QtWidgets.QVBoxLayout(editorFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.inputEnterFrameBase = InputEnterFrame(parent=editorFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputEnterFrameBase.sizePolicy().hasHeightForWidth())
        self.inputEnterFrameBase.setSizePolicy(sizePolicy)
        self.inputEnterFrameBase.setObjectName("inputEnterFrameBase")
        self.verticalLayout.addWidget(self.inputEnterFrameBase)
        self.bottomToolFrame = QtWidgets.QFrame(parent=editorFrame)
        self.bottomToolFrame.setMinimumSize(QtCore.QSize(0, 60))
        self.bottomToolFrame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.bottomToolFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.bottomToolFrame.setObjectName("bottomToolFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.bottomToolFrame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftSwitchButton = QtWidgets.QToolButton(parent=self.bottomToolFrame)
        self.leftSwitchButton.setMinimumSize(QtCore.QSize(60, 60))
        self.leftSwitchButton.setObjectName("leftSwitchButton")
        self.horizontalLayout.addWidget(self.leftSwitchButton)
        self.createNewButton = QtWidgets.QToolButton(parent=self.bottomToolFrame)
        self.createNewButton.setMinimumSize(QtCore.QSize(60, 60))
        self.createNewButton.setObjectName("createNewButton")
        self.horizontalLayout.addWidget(self.createNewButton)
        self.saveButton = QtWidgets.QToolButton(parent=self.bottomToolFrame)
        self.saveButton.setMinimumSize(QtCore.QSize(60, 60))
        self.saveButton.setObjectName("confirmButton")
        self.horizontalLayout.addWidget(self.saveButton)
        self.rightSwitchButton = QtWidgets.QToolButton(parent=self.bottomToolFrame)
        self.rightSwitchButton.setMinimumSize(QtCore.QSize(60, 60))
        self.rightSwitchButton.setObjectName("rightSwitchButton")
        self.horizontalLayout.addWidget(self.rightSwitchButton)
        self.verticalLayout.addWidget(self.bottomToolFrame)

        self.retranslateUi(editorFrame)
        QtCore.QMetaObject.connectSlotsByName(editorFrame)

    def retranslateUi(self, editorFrame):
        _translate = QtCore.QCoreApplication.translate
        editorFrame.setWindowTitle(_translate("editorFrame", "Form"))
        self.leftSwitchButton.setText(_translate("editorFrame", "<-"))
        self.createNewButton.setText(_translate("editorFrame", "new"))
        self.saveButton.setText(_translate("editorFrame", "confirm"))
        self.rightSwitchButton.setText(_translate("editorFrame", "->"))
from QtUI.views.inputEnterFrame import InputEnterFrame
