# Form implementation generated from reading ui file '/Users/lennon/Library/Mobile Documents/com~apple~CloudDocs/Useful files/Projects/Time_Integrater/QtUI/views/rawUI/rawPropertyEnterFrame.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_propertyEnterFrame(object):
    def setupUi(self, propertyEnterFrame):
        propertyEnterFrame.setObjectName("propertyEnterFrame")
        propertyEnterFrame.resize(650, 173)
        self.horizontalLayout = QtWidgets.QHBoxLayout(propertyEnterFrame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.propertyEntries = QtWidgets.QFrame(parent=propertyEnterFrame)
        self.propertyEntries.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.propertyEntries.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.propertyEntries.setObjectName("propertyEntries")
        self.formLayout = QtWidgets.QFormLayout(self.propertyEntries)
        self.formLayout.setObjectName("formLayout")
        self.startLabel = QtWidgets.QLabel(parent=self.propertyEntries)
        self.startLabel.setObjectName("startLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.startLabel)
        self.startEdit = QtWidgets.QLineEdit(parent=self.propertyEntries)
        self.startEdit.setObjectName("startEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.startEdit)
        self.endLabel = QtWidgets.QLabel(parent=self.propertyEntries)
        self.endLabel.setObjectName("endLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.endLabel)
        self.endEdit = QtWidgets.QLineEdit(parent=self.propertyEntries)
        self.endEdit.setObjectName("endEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.endEdit)
        self.actionTypeLabel = QtWidgets.QLabel(parent=self.propertyEntries)
        self.actionTypeLabel.setObjectName("actionTypeLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.actionTypeLabel)
        self.actionTypeEdit = QtWidgets.QLineEdit(parent=self.propertyEntries)
        self.actionTypeEdit.setObjectName("actionTypeEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.actionTypeEdit)
        self.actionLabel = QtWidgets.QLabel(parent=self.propertyEntries)
        self.actionLabel.setObjectName("actionLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.actionLabel)
        self.actionEdit = RealTimeSearchEdit(parent=self.propertyEntries)
        self.actionEdit.setObjectName("actionEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.actionEdit)
        self.horizontalLayout.addWidget(self.propertyEntries)
        self.propertyEntries_2 = QtWidgets.QFrame(parent=propertyEnterFrame)
        self.propertyEntries_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.propertyEntries_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.propertyEntries_2.setObjectName("propertyEntries_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.propertyEntries_2)
        self.formLayout_2.setObjectName("formLayout_2")
        self.actionDetailLabel = QtWidgets.QLabel(parent=self.propertyEntries_2)
        self.actionDetailLabel.setObjectName("actionDetailLabel")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.actionDetailLabel)
        self.actionDetailEdit = QtWidgets.QLineEdit(parent=self.propertyEntries_2)
        self.actionDetailEdit.setObjectName("actionDetailEdit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.actionDetailEdit)
        self.urgenCheckBox = QtWidgets.QCheckBox(parent=self.propertyEntries_2)
        self.urgenCheckBox.setObjectName("urgenCheckBox")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.urgenCheckBox)
        self.imporCheckBox = QtWidgets.QCheckBox(parent=self.propertyEntries_2)
        self.imporCheckBox.setObjectName("imporCheckBox")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.imporCheckBox)
        self.horizontalLayout.addWidget(self.propertyEntries_2)

        self.retranslateUi(propertyEnterFrame)
        QtCore.QMetaObject.connectSlotsByName(propertyEnterFrame)

    def retranslateUi(self, propertyEnterFrame):
        _translate = QtCore.QCoreApplication.translate
        propertyEnterFrame.setWindowTitle(_translate("propertyEnterFrame", "Form"))
        self.startLabel.setText(_translate("propertyEnterFrame", "Start"))
        self.endLabel.setText(_translate("propertyEnterFrame", "End"))
        self.actionTypeLabel.setText(_translate("propertyEnterFrame", "ActionType"))
        self.actionLabel.setText(_translate("propertyEnterFrame", "Action"))
        self.actionDetailLabel.setText(_translate("propertyEnterFrame", "ActionDetail"))
        self.urgenCheckBox.setText(_translate("propertyEnterFrame", "urgency"))
        self.imporCheckBox.setText(_translate("propertyEnterFrame", "importance"))
from QtUI.widgets.other.RealTimeSearchEdit import RealTimeSearchEdit
