# Form implementation generated from reading ui file '/Users/lennon/Library/Mobile Documents/com~apple~CloudDocs/Useful files/Projects/Time_Integrater/QtUI/views/rawUI/rawDateSelectionFrame.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dateSelection(object):
    def setupUi(self, dateSelection):
        dateSelection.setObjectName("dateSelection")
        dateSelection.resize(607, 434)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(dateSelection.sizePolicy().hasHeightForWidth())
        dateSelection.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(dateSelection)
        self.verticalLayout.setObjectName("verticalLayout")
        self.calendarWidget = QtWidgets.QCalendarWidget(parent=dateSelection)
        self.calendarWidget.setObjectName("calendarWidget")
        self.verticalLayout.addWidget(self.calendarWidget)
        self.comboBox = QtWidgets.QComboBox(parent=dateSelection)
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout.addWidget(self.comboBox)
        self.dateEditFrame = QtWidgets.QFrame(parent=dateSelection)
        self.dateEditFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.dateEditFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.dateEditFrame.setObjectName("dateEditFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.dateEditFrame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(parent=self.dateEditFrame)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.horizontalLayout.addWidget(self.dateTimeEdit)
        self.newRecordButton = QtWidgets.QPushButton(parent=self.dateEditFrame)
        self.newRecordButton.setObjectName("newRecordButton")
        self.horizontalLayout.addWidget(self.newRecordButton)
        self.verticalLayout.addWidget(self.dateEditFrame)
        self.label = QtWidgets.QLabel(parent=dateSelection)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)

        self.retranslateUi(dateSelection)
        QtCore.QMetaObject.connectSlotsByName(dateSelection)

    def retranslateUi(self, dateSelection):
        _translate = QtCore.QCoreApplication.translate
        dateSelection.setWindowTitle(_translate("dateSelection", "Form"))
        self.newRecordButton.setText(_translate("dateSelection", "create new record"))
        self.label.setText(_translate("dateSelection", "combobox and calender is future function, enter <enter> when you focus on the widget to enter in"))
