# Form implementation generated from reading ui file '/Users/lennon/Library/Mobile Documents/com~apple~CloudDocs/Useful files/Projects/Time_Integrater/QtUI/views/rawUI/rawFastEntry.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_rawFastEnterFrame(object):
    def setupUi(self, rawFastEnterFrame):
        rawFastEnterFrame.setObjectName("rawFastEnterFrame")
        rawFastEnterFrame.resize(578, 198)
        self.horizontalLayout = QtWidgets.QHBoxLayout(rawFastEnterFrame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.fastEntryLabel = QtWidgets.QLabel(parent=rawFastEnterFrame)
        self.fastEntryLabel.setObjectName("fastEntryLabel")
        self.horizontalLayout.addWidget(self.fastEntryLabel)
        self.fastEntry = QtWidgets.QLineEdit(parent=rawFastEnterFrame)
        self.fastEntry.setObjectName("fastEntry")
        self.horizontalLayout.addWidget(self.fastEntry)

        self.retranslateUi(rawFastEnterFrame)
        QtCore.QMetaObject.connectSlotsByName(rawFastEnterFrame)

    def retranslateUi(self, rawFastEnterFrame):
        _translate = QtCore.QCoreApplication.translate
        rawFastEnterFrame.setWindowTitle(_translate("rawFastEnterFrame", "Form"))
        self.fastEntryLabel.setText(_translate("rawFastEnterFrame", "fast entry"))
