# Form implementation generated from reading ui file '/Users/lennon/Projects/Time_Integrater/ti/UI/rawUI/InterventionCard.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_interventionWidget(object):
    def setupUi(self, interventionWidget):
        interventionWidget.setObjectName("interventionWidget")
        interventionWidget.resize(706, 546)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(interventionWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(parent=interventionWidget)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleWidget = QtWidgets.QWidget(parent=self.frame)
        self.titleWidget.setObjectName("titleWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.titleWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.title = QtWidgets.QLabel(parent=self.titleWidget)
        self.title.setText("")
        self.title.setObjectName("title")
        self.horizontalLayout.addWidget(self.title)
        self.verticalLayout.addWidget(self.titleWidget)
        self.choiceWidget = QtWidgets.QWidget(parent=self.frame)
        self.choiceWidget.setObjectName("choiceWidget")
        self.choiceLayout = QtWidgets.QHBoxLayout(self.choiceWidget)
        self.choiceLayout.setContentsMargins(0, 0, 0, 0)
        self.choiceLayout.setObjectName("choiceLayout")
        self.verticalLayout.addWidget(self.choiceWidget)
        self.verticalLayout_2.addWidget(self.frame)

        self.retranslateUi(interventionWidget)
        QtCore.QMetaObject.connectSlotsByName(interventionWidget)

    def retranslateUi(self, interventionWidget):
        _translate = QtCore.QCoreApplication.translate
        interventionWidget.setWindowTitle(_translate("interventionWidget", "Form"))
