@startuml
title Conditional_Card_Generation

participant "CardController: controller" as controller
participant "Conditional_ReportGenerator: generator" as generator
participant "InsightEngine: engine" as engine
participant "Detectors: detector" as detector
participant "Presenters: presenter" as presenter
participant "InsightManager: manager" as manager

activate controller

controller -> generator: create_report()
activate generator

' 开始喂数据
loop for au in data: 
    generator -> engine: process_event(au: dict)
    activate engine

    loop for id in self.cards:
        ' Detector匹配
        engine -> detector: process_event(au)
        ref over detector: [2]detector_activity.puml
        activate detector
        
        detector --> engine: pattern_detected(insight_pack)
        deactivate detector

        ' Presenter处理
        engine -> presenter: __call__(insight_pack: dict) -> dict
        activate presenter

        presenter --> engine: return present_pack: dict
        deactivate presenter

        ' 模式匹配, 发送信号
        engine --> generator: _on_pattern_detected.emit((rawData,preData))
        deactivate engine

        ' Manager
        generator -> manager: add_card(insight_pack: dict,present_pack: dict)
        activate manager
        deactivate manager

    end

    ' Engine执行完毕
    deactivate engine
end

' generator调用，展示数据
generator -> manager: get_current_cards()
activate manager

note over manager: 进行内部的重要程度排序
manager --> generator: return cards: list
deactivate manager

generator --> controller: return card_data: list
deactivate generator 
@enduml