# Form implementation generated from reading ui file '/Users/lennon/Projects/Time_Integrater/QtUI/rawUI/rawCapturePage.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CapturePage(object):
    def setupUi(self, CapturePage):
        CapturePage.setObjectName("CapturePage")
        CapturePage.resize(876, 647)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(CapturePage.sizePolicy().hasHeightForWidth())
        CapturePage.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(CapturePage)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mainFrame = QtWidgets.QWidget(parent=CapturePage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainFrame.sizePolicy().hasHeightForWidth())
        self.mainFrame.setSizePolicy(sizePolicy)
        self.mainFrame.setObjectName("mainFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.mainFrame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftToolFrame = QtWidgets.QFrame(parent=self.mainFrame)
        self.leftToolFrame.setMinimumSize(QtCore.QSize(100, 0))
        self.leftToolFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.leftToolFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.leftToolFrame.setObjectName("leftToolFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.leftToolFrame)
        self.verticalLayout_2.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.editorFrameButton = QtWidgets.QRadioButton(parent=self.leftToolFrame)
        self.editorFrameButton.setMinimumSize(QtCore.QSize(30, 0))
        self.editorFrameButton.setObjectName("editorFrameButton")
        self.enterModeGroup = QtWidgets.QButtonGroup(CapturePage)
        self.enterModeGroup.setObjectName("enterModeGroup")
        self.enterModeGroup.addButton(self.editorFrameButton)
        self.verticalLayout_2.addWidget(self.editorFrameButton)
        self.bulkEnterFrameButton = QtWidgets.QRadioButton(parent=self.leftToolFrame)
        self.bulkEnterFrameButton.setMinimumSize(QtCore.QSize(30, 0))
        self.bulkEnterFrameButton.setObjectName("bulkEnterFrameButton")
        self.enterModeGroup.addButton(self.bulkEnterFrameButton)
        self.verticalLayout_2.addWidget(self.bulkEnterFrameButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.leftToolFrame)
        self.splitterFrame = QtWidgets.QFrame(parent=self.mainFrame)
        self.splitterFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.splitterFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.splitterFrame.setObjectName("splitterFrame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.splitterFrame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.splitter = QtWidgets.QSplitter(parent=self.splitterFrame)
        self.splitter.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.splitter.setOpaqueResize(True)
        self.splitter.setObjectName("splitter")
        self.dateSelectionFrameBase = DateSelectionFrame(parent=self.splitter)
        self.dateSelectionFrameBase.setObjectName("dateSelectionFrameBase")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.splitter)
        self.stackedWidget.setObjectName("stackedWidget")
        self.editorFrameBase = EditorFrame()
        self.editorFrameBase.setObjectName("editorFrameBase")
        self.stackedWidget.addWidget(self.editorFrameBase)
        self.bulkEnterFrameBase = BulkEnterFrame()
        self.bulkEnterFrameBase.setObjectName("bulkEnterFrameBase")
        self.stackedWidget.addWidget(self.bulkEnterFrameBase)
        self.horizontalLayout_3.addWidget(self.splitter)
        self.horizontalLayout.addWidget(self.splitterFrame)
        self.verticalLayout.addWidget(self.mainFrame)
        self.pageSwitchFrameBase = PageSwitchFrame(parent=CapturePage)
        self.pageSwitchFrameBase.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.pageSwitchFrameBase.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.pageSwitchFrameBase.setObjectName("pageSwitchFrameBase")
        self.verticalLayout.addWidget(self.pageSwitchFrameBase)

        self.retranslateUi(CapturePage)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(CapturePage)

    def retranslateUi(self, CapturePage):
        _translate = QtCore.QCoreApplication.translate
        CapturePage.setWindowTitle(_translate("CapturePage", "Form"))
        self.editorFrameButton.setText(_translate("CapturePage", "basic enter"))
        self.bulkEnterFrameButton.setText(_translate("CapturePage", "bulk mode"))
from QtUI.views.capture.bulkEnterFrame import BulkEnterFrame
from QtUI.views.capture.dateSelectionFrame import DateSelectionFrame
from QtUI.views.capture.editorFrame import EditorFrame
from QtUI.views.pageSwitchFrame import PageSwitchFrame
