# Form implementation generated from reading ui file '/Users/lennon/Projects/Time_Integrater/QtUI/rawUI/rawPageSwitchFrame.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_pageswitchFrame(object):
    def setupUi(self, pageswitchFrame):
        pageswitchFrame.setObjectName("pageswitchFrame")
        pageswitchFrame.resize(555, 66)
        pageswitchFrame.setMinimumSize(QtCore.QSize(0, 50))
        self.horizontalLayout = QtWidgets.QHBoxLayout(pageswitchFrame)
        self.horizontalLayout.setContentsMargins(0, 3, 0, 3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.menuButton = QtWidgets.QToolButton(parent=pageswitchFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.menuButton.sizePolicy().hasHeightForWidth())
        self.menuButton.setSizePolicy(sizePolicy)
        self.menuButton.setMinimumSize(QtCore.QSize(90, 30))
        font = QtGui.QFont()
        font.setFamily("AppleGothic")
        font.setPointSize(20)
        self.menuButton.setFont(font)
        self.menuButton.setObjectName("menuButton")
        self.horizontalLayout.addWidget(self.menuButton)
        self.captureButton = QtWidgets.QToolButton(parent=pageswitchFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.captureButton.sizePolicy().hasHeightForWidth())
        self.captureButton.setSizePolicy(sizePolicy)
        self.captureButton.setMinimumSize(QtCore.QSize(90, 30))
        font = QtGui.QFont()
        font.setFamily("AppleGothic")
        font.setPointSize(20)
        self.captureButton.setFont(font)
        self.captureButton.setObjectName("captureButton")
        self.horizontalLayout.addWidget(self.captureButton)
        self.analysisButton = QtWidgets.QToolButton(parent=pageswitchFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.analysisButton.sizePolicy().hasHeightForWidth())
        self.analysisButton.setSizePolicy(sizePolicy)
        self.analysisButton.setMinimumSize(QtCore.QSize(90, 30))
        font = QtGui.QFont()
        font.setFamily("AppleGothic")
        font.setPointSize(20)
        self.analysisButton.setFont(font)
        self.analysisButton.setObjectName("analysisButton")
        self.horizontalLayout.addWidget(self.analysisButton)
        self.settingButton = QtWidgets.QToolButton(parent=pageswitchFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.settingButton.sizePolicy().hasHeightForWidth())
        self.settingButton.setSizePolicy(sizePolicy)
        self.settingButton.setMinimumSize(QtCore.QSize(90, 30))
        font = QtGui.QFont()
        font.setFamily("AppleGothic")
        font.setPointSize(20)
        self.settingButton.setFont(font)
        self.settingButton.setObjectName("settingButton")
        self.horizontalLayout.addWidget(self.settingButton)

        self.retranslateUi(pageswitchFrame)
        QtCore.QMetaObject.connectSlotsByName(pageswitchFrame)

    def retranslateUi(self, pageswitchFrame):
        _translate = QtCore.QCoreApplication.translate
        pageswitchFrame.setWindowTitle(_translate("pageswitchFrame", "Form"))
        self.menuButton.setText(_translate("pageswitchFrame", "Start"))
        self.captureButton.setText(_translate("pageswitchFrame", "Capture"))
        self.analysisButton.setText(_translate("pageswitchFrame", "Analysis"))
        self.settingButton.setText(_translate("pageswitchFrame", "Strategy and Settings"))
